preprocessing:
  baseline: null 
  l_freq: 1
  h_freq: 100
  tmin: 4.433333333333334
  tmax: 11.1
  channels_to_drop:
    - VEO
    - HEO
    - M1
    - M2
    - EKG
    - EMG
    - HEOL
    - HEOR
  reference_channels: 'average'
  resample_freq: 100
  random_state: 42

analysis:
  fmin: 1
  fmax: 25 
  noise_n_neighbor_bins: 1
  noise_skip_neighbor_bins: 0
  vROIs:
    - PO7
    - PO5
    - PO3
    - CB1
    - O1
    - POZ
    - OZ
    - PO4
    - PO6
    - PO8
    - CB2
    - O2

bands:
  theta:
    - 4
    - 8
  alpha:
    - 8
    - 12
  low_beta:
    - 12.5
    - 16
  beta:
    - 16.5
    - 25
