preprocessing:
  l_freq: 0.5
  h_freq: 100
  channels_to_drop:
    - EMG
    - EKG
    - VEO
    - HEO
    - HEOL
    - HEOR
    - M1
    - M2
  resample_freq: 100
  random_state: 42

bands:
  theta:
    - 4
    - 8
  alpha:
    - 8
    - 12
  low_beta:
    - 12.5
    - 16
  beta:
    - 16.5
    - 25

